resilience4j.circuitbreaker:
    instances:
        userService:
            slidingWindowSize: 10
            failureRateThreshold: 50
            waitDurationInOpenState: 30s
        imageService:
            slidingWindowSize: 5
            failureRateThreshold: 50
            waitDurationInOpenState: 20s